navigation:
 - text: Home
   url: /
 - text: Blog
   url: /blog/
 - text: Resume
   url: /resume/
 - text: Projects
   url: /projects/

markdown: redcarpet
highlighter: pygments

paginate: 5
paginate_path: "/blog/page:num/"