navigation:
 - text: Home
   url: /
 - text: Blog
   url: /blog/
 - text: Resume
   url: /resume/
 - text: Projects
   url: /projects/
 - text: Publications
   url: /publications/

kramdown:
    input: GFM
    syntax_highlighter: rouge

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
